<?php if($error): ?>
    <div class="alert alert-danger" role="alert">
    <?= $error ?>
    </div>
<?php endif ?>

<form action="do_login" method="POST">
    <div class="form-group">
        <label for="email">Gmail</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-group">
        <label for="nombre">Nombre de usuario</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
</form>