<?php if($error): ?>
    <div class="alert alert-danger" role="alert">
    <?= $error ?>
    </div>
<?php endif ?>

<form action="login" method="POST">
    <div class="form-group">
        <label for="gmail">Gmail</label>
        <input type="gmail" class="form-control" id="gmail" name="gmail" required>
    </div>
    <div class="form-group">
        <label for="usuario">Nombre de usuario</label>
        <input type="text" class="form-control" id="usuario" name="usuario" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
</form>