<div>
    <h3>Agregar Nuevo Viaje</h3>
    <form action="<?= BASE_URL ?>agregarViaje" method="POST" novalidate>
        <div class="col1">
            <label for="fecha">Fecha de Viaje</label>
            <input type="date" id="fecha" name="fecha" required>
        </div>

        <div class="col1">
            <label for="origen">Origen</label>
            <input type="text" id="origen" name="origen" required>
        </div>
        <div class="col1">
            <label for="destino">Destino</label>
            <input type="text" id="destino" name="destino" required>
        </div>
        <div class="col1">
            <label for="ID_conductor">Conductor</label>
    <select name="ID_conductor" id="ID_conductor" required>
        <option value="">-- Seleccionar Conductor --</option>
        <?php foreach ($conductores as $conductor): ?>
            <option value="<?= $conductor->ID_conductor ?>">
                <?= htmlspecialchars($conductor->nombre) ?> — <?= htmlspecialchars($conductor->vehiculo) ?>
            </option>
        <?php endforeach; ?>
    </select>
        </div>
        <div class="col1">
            <button type="submit">Agregar Viaje</button>
        </div>

</div>
</form>
</div>