<div >
    <h3>Detalles del Viaje</h3>

    <div>
        <div>
            <ul>
            <li ><strong>Fecha:</strong> <?= $viaje->fecha ?></li>
                <li><strong>Origen:</strong> <?= $viaje->origen ?></li>
                <li ><strong>Destino:</strong> <?= $viaje->destino ?></li>
                <li><strong>Nombre:</strong> <?=$conductor->nombre?></li>
                <li><strong>Vehiculo:</strong><?=$conductor->vehiculo?></li>
            </ul>
        </div>
    </div>
</div>